/**
 * KRTR Compiled Circuits
 * Auto-generated by build-circuits.sh
 */

import membershipCircuit from './membership.json';
import reputationCircuit from './reputation.json';
import messageProofCircuit from './message_proof.json';

export {
  membershipCircuit,
  reputationCircuit,
  messageProofCircuit
};
